### PR TITLE
CHIA-880 Remove no longer needed debug in SpendBundle

### PR DESCRIPTION
**Pull request by AmineKhaldi**

### CODE REVIEW

**Comment by Rigidity** [comment]
@AmineKhaldi can you rebase against main? The CI issue should be fixed

**Comment by AmineKhaldi** [comment]
> @AmineKhaldi can you rebase against main? The CI issue should be fixed

Done.

**Comment by Rigidity** [comment]
This just needs to be removed from the bindings in generate_type_stubs.py (then that script run to update the autogenerated file)

Otherwise lgtm

**Comment by AmineKhaldi** [comment]
> This just needs to be removed from the bindings in generate_type_stubs.py (then that script run to update the autogenerated file)
> 
> Otherwise lgtm

Done.

**Review by Rigidity — APPROVED** [review]

**Pull request merged**
