### PR TITLE
Add needed items for sdist

### PR DESCRIPTION
**Pull request by emlowe**
Add in some missing bits in wheel/Cargo.toml and some hacks around missing parts in the tar archive

Main items are:
needing to add in `chia-client` and `chia-ssl` to `wheel/Cargo.toml`
needing to remove the `../LICENSE` from `wheel/Cargo.toml` - this resulted in the tar not having the LICENSE file but also pip expecting it, so I just removed it for now.
I noticed the tar was missing the `src` directory, so I had to manually add in the src directory to the tar archive. 

This does make a` tar.gz` that does build on my riscv machine and also my mac.

### CODE REVIEW

**Review by arvidn — COMMENTED** [review]
It's not obvious why `chia-client` and `chia-ssl` are needed to build the wheel. Is maturin failing to bundle transitive dependencies? I wouldn't expect these to be part of the dependency tree at all though

**Comment by emlowe** [comment]
When maturin builds the sdist, it puts in the tar the `Cargo.toml` from the root workspace and not from the wheel directory. They are listed in the root Cargo as deps and default features.

**Review by arvidn — APPROVED** [review]

**Comment by arvidn** [comment]
I see. thanks for the explanation.

**Review by Rigidity — APPROVED** [review]
lgtm for now

**Pull request merged**
